### ISSUE TITLE
how to use the BioImage Suite Web to identify electrode locations

### ISSUE THREAD

**Issue by linrongqi** [bioimagesuiteweb/bisweb#118]
Deal all,
Hi!
I want to use the BioImage Suite to identify electrode locations in human's brain, however, i found that there was not the BioImage Suite, but the BioImage Suite web. I want to know where the BioImage Suite web could  identify electrode locations and how?
Thank you !
Rongqi lin.

**Comment by XeniosP** [comment]
Unfortunately this is still work in progress. We are trying to find supporting to implement this.
