### ISSUE TITLE
Battery life and CPU usage

### ISSUE THREAD

**Issue by neurolabusc** [bioimagesuiteweb/bisweb#122]
When viewing a volume with BioimageSuite I see high CPU usage (and presumably poor battery life). I do not see this behavior when viewing the same volume with JavaScript tools that refresh the canvas only when needed, for example [MRIcroWeb](https://github.com/rordenlab/MRIcroWeb). 

Since BioimageSuite is showing static scenes that only change when the user interacts with the window, I would suggest not having the tool automatically refresh. I believe [this page](https://stackoverflow.com/questions/52909816/advice-on-improving-threejs-performance) describes the solution.

**Comment by bioimagesuiteweb** [comment]
I think we do a bad job of updating, its straight up 60Hz rendering that probably overloads the CPU. Let me take a look. Thanks!

**Comment by XeniosP** [comment]
I put an update in the source tree that removes unnecessary renders. Test version coming soon.

**Comment by XeniosP** [comment]
https://bioimagesuiteweb.github.io/alphaapp/

**Comment by XeniosP** [comment]
The patch seems to be working
