### ISSUE TITLE
BAD BAD BAD ... -- bisweb dislikes something about something in a nii.gz "file"

### ISSUE THREAD

**Issue by yarikoptic** [bioimagesuiteweb/bisweb#127]
https://bioimagesuiteweb.github.io/webapp/viewer.html?image=https://datasets.datalad.org/.git/tmp/blah.nii.gz on a copy of the file served from elsewhere works -- so it is not about content but either about failing to deduce extension (is content-disposition considered?) or something else since all the following do not work

- https://bioimagesuiteweb.github.io/webapp/viewer.html?image=https://dandiarchive.s3.amazonaws.com/blobs/472/10e/47210e31-7e86-4a9d-bcad-413825c4250a  (direct link to the blob on S3 -- no extension), 
- https://bioimagesuiteweb.github.io/webapp/viewer.html?image=https%3A//dandiarchive.s3.amazonaws.com/blobs/472/10e/47210e31-7e86-4a9d-bcad-413825c4250a%3Fresponse-content-disposition%3Dattachment%253B%2520filename%253D%2522average_template_50.nii.gz%2522%26X-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Credential%3DAKIAUBRWC5GAEKH3223E%252F20210817%252Fus-east-2%252Fs3%252Faws4_request%26X-Amz-Date%3D20210817T230946Z%26X-Amz-Expires%3D3600%26X-Amz-SignedHeaders%3Dhost%26X-Amz-Signature%3D92b112581193205dc7fded65a0b9168daf202132c07f3190e83a72840e5b5840 - url encoded, signed URL with content-disposition provided (probably would expire soon)
- https://bioimagesuiteweb.github.io/webapp/viewer.html?image=https://api.dandiarchive.org/api/assets/5ab0247b-659a-4593-b251-b338676de725/download/ -- uses original url which mints the presigned URL used above.

Ideally -- all of them should work ;) but console says

![image](https://user-images.githubusercontent.com/39889/129812952-435a17af-f8d3-460b-a174-f8aacb7d2aee.png)

**Comment by XeniosP** [comment]
W.r.t. https://bioimagesuiteweb.github.io/webapp/viewer.html?image=https://dandiarchive.s3.amazonaws.com/blobs/472/10e/47210e31-7e86-4a9d-bcad-413825c4250a (direct link to the blob on S3 -- no extension),

BIS looks for a .gz extension to decide if to uncompress or not. If it does not find it, then it assumes that it is uncompressed and fails. I guess I can add a flag that if it fails uncompressed to then try to uncompress the file.

**Comment by yarikoptic** [comment]
isn't there some JS equivalent of https://man7.org/linux/man-pages/man3/magic_getflags.3.html even if only for a few needed here "fingerprints" (well -- single one for -- `gz`).   google lead me to https://github.com/mscdex/mmmagic .

 You could also, in case of exception like this, just try to assume that it is compressed and try to uncompress without sensing -- what evil could happen?

**Comment by XeniosP** [comment]
Try using the alphaapp -- I pushed a fix there.

https://bioimagesuiteweb.github.io/alphaapp/viewer.html

**Comment by yarikoptic** [comment]
FWIW: https://bioimagesuiteweb.github.io/alphaapp/viewer.html?image=https://dandiarchive.s3.amazonaws.com/blobs/472/10e/47210e31-7e86-4a9d-bcad-413825c4250a works for me ... and even https://bioimagesuiteweb.github.io/alphaapp/viewer.html?image=https://api.dandiarchive.org/api/assets/5ab0247b-659a-4593-b251-b338676de725/download/ works -- woohoo!!

**Comment by yarikoptic** [comment]
how fast alphaapp grows into app? ;)

**Comment by XeniosP** [comment]
Basically, the stupid solution. If it fails force gunzip and try again. 

W.r.t. alphapp, usually we go alphaapp --> unstableapp --> webapp.

alphaapp is a playground

Once you test it and you are happy, I will move to unstableapp which despite the name stays like that for a while.

New "webapp" probably November/December.

Xenios

**Comment by yarikoptic** [comment]
I think I am happier than before.  is it ok to just link out to "unstableapp" until the winter comes?  would allow for more testing etc ;)

**Comment by XeniosP** [comment]
Done. It might take a few minutes before github updates the pages.

Xenios

**Comment by XeniosP** [comment]
It is there, force the page to reload if you need to

https://bioimagesuiteweb.github.io/unstableapp/viewer.html

(You can tell if it is updated by the date in the bottom right corner on the status bar)

**Comment by yarikoptic** [comment]
I meant, if it would be ok to link out to it from dandiarchive.org ;-) relevant draft pr: https://github.com/dandi/dandiarchive/pull/849
