### ISSUE TITLE
Unable to Load Different Atlas into Web Connectivity Viewer

### ISSUE THREAD

**Issue by nolanrbrady** [bioimagesuiteweb/bisweb#140]
Hi,
I am trying to load a nifti file of the Gordon 2026 atlas into BioImage Suite using the "Advanced -> Import Parcellation Image" option. I don't see any changes in the GUI (i.e it keep showing the atlas as the Shen et al 268 parcellation atlas). I'm not certain if I am uploading the new parcellation incorrectly or if there is an issue with the functionality. Any help you may be able to provide would be greatly appreciated. Thank you!

**Comment by bioimagesuiteweb** [comment]
Please share a link to the image

Sent from a mobile device.
________________________________
From: Nolan Brady ***@***.***>
Sent: Tuesday, June 4, 2024 7:43:12 PM
To: bioimagesuiteweb/bisweb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bioimagesuiteweb/bisweb] Unable to Load Different Atlas into Web Connectivity Viewer (Issue #140)


Hi,
I am trying to load a nifti file of the Gordon 2026 atlas into BioImage Suite using the "Advanced -> Import Parcellation Image" option. I don't see any changes in the GUI (i.e it keep showing the atlas as the Shen et al 268 parcellation atlas). I'm not certain if I am uploading the new parcellation incorrectly or if there is an issue with the functionality. Any help you may be able to provide would be greatly appreciated. Thank you!

**Comment by nolanrbrady** [comment]
Hi,
Thank you for your response. I am using the nii.gz file from this github repository.
https://github.com/brainspaces/gordon333

Looking further into the issue, it seems that in the console I get the following error:
<img width="739" alt="Screenshot 2024-06-11 at 5 27 00 PM" src="https://github.com/bioimagesuiteweb/bisweb/assets/26473798/88a5258a-298e-409e-b7e8-7876d2765886">
I have tried converting the image to the RAS orientation mentioned in the error message but it doesn't change the error message.

**Comment by XeniosP** [comment]
Try using this one. It is a stupid little thing -- we expect images to be
181x217x181 (the old MNI size) and newer ones are 182x218x182. I remapped
it a bit.

Xenios

**Comment by nolanrbrady** [comment]
@XeniosP That makes sense, thank you for the help! I'm not sure if you meant to attach something to your message but I'm not seeing an attached image. Would you mind reuploading it? I would do it myself but I'm not familiar with converting between old and new MNI images. Thank you again!

**Comment by bioimagesuiteweb** [comment]
Could you email me directly @xenophon dot papademetris @yale.edu

Sent from a mobile device.
________________________________
