### ISSUE TITLE
Makes my firefox sweat too much (and it is winter here!)

### ISSUE THREAD

**Issue by yarikoptic** [bioimagesuiteweb/bisweb#99]
Opening https://bioimagesuiteweb.github.io/webapp/viewer.html?image=https://datasets.datalad.org/labs/haxby/raiders/derivatives/openfmrilayout-qa-defacing/defacing/alldefaced_mean.nii.gz leads my firefox to become extremely busy after a while.  Not yet sure what triggers it (screen lock or something else). Firefox from debian 68.2.0esr (64-bit). Closing and reopening the page didn't yet trigger high CPU load.  I am filing the report to seek instructions on what to do/check whenever cpu becomes too busy next time.

**Comment by XeniosP** [comment]
Don't use firefox -- we don't test with this. Unfortunately Chrome (Chromium) has become the defacto standard.
